address: 0.0.0.0  
pid: /home/ubuntu/node_acclerate/shared/tmp/pids/thin.pid  
wait: 30  
port: 3000  
timeout: 30  
log: /home/ubuntu/node_acclerate/shared/log/thin.log  
max_conns: 1024  
require: []  
  
environment: production  
secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
max_persistent_conns: 512  
servers: 1 
daemonize: true  
chdir: /home/ubuntu/node_acclerate/current