address: 0.0.0.0  
pid: tmp/pids/thin.pid  
wait: 30  
port: 3000  
timeout: 30  
log: log/thin.log  
max_conns: 1024  
require: []  
  
environment: production  
max_persistent_conns: 512  
servers: 1 
daemonize: true